"""Generate LLVM/LLD include data from the typed ELF ABI catalog."""

from __future__ import annotations

from types import MappingProxyType


import re
from typing import NamedTuple

from abi.elf.model.projection import ElfAbiProjection, project_elf_abi
from abi.elf.model.relocation_metasyntax import RelocationExpression
from abi.elf.model.project import Relocation
from engine.artifacts.generate import ArtifactGenerationContext
from engine.artifacts.definition import GeneratedArtifact, GeneratedArtifactSet



_LLD_EXPRESSION_SIGNATURES = MappingProxyType({
    "(+ symbol addend)": "ABS",
    "copy(symbol,symbol_size)": "ABS",
    "resolver((+ load_base addend))": "ABS",
    "(+ load_base addend)": "ABS",
    "(- (+ symbol addend) place)": "PC",
    "(- (+ symbol addend) next_pc)": "PC",
    "(- (+ symbol addend) section_base)": "SECTION_REL",
    "(- (+ plt(symbol) addend) next_pc)": "PLT_PC",
    "(+ plt(symbol) addend)": "PLT",
    "(+ got(symbol) addend)": "GOT",
    "(- (+ got(symbol) addend) place)": "GOT_PC",
    "(- (+ symbol addend) got_base)": "GOTPLTREL",
    "(- (+ got_base addend) place)": "GOTPLTONLY_PC",
    "(+ tls(symbol) addend)": "TPREL",
    "(- (+ tlsdesc(symbol) addend) place)": "TLSDESC_PC",
    "tls_descriptor(symbol)": "TLSDESC",
})

_MACROS = (
    "BEDROCK_ELF_RELOCATION",
    "BEDROCK_ELF_RELAXATION",
    "BEDROCK_ELF_CODE_MODEL",
    "BEDROCK_ELF_CODE_MODEL_RELOCATION",
    "BEDROCK_ELF_TLS_MODEL",
    "BEDROCK_ELF_TLS_MODEL_RELOCATION",
    "BEDROCK_ELF_TLS_PROPERTY",
    "BEDROCK_ELF_LINKAGE_PROTOCOL",
    "BEDROCK_ELF_LINKAGE_STEP",
    "BEDROCK_ELF_LINKAGE_REGISTER",
    "BEDROCK_ELF_LINKAGE_PROPERTY",
    "BEDROCK_ELF_DEBUG_REGISTER_RANGE",
    "BEDROCK_ELF_DEBUG_REGISTER_MAPPING",
    "BEDROCK_ELF_ENTRY_STATE",
    "BEDROCK_ELF_ENTRY_STACK_PERMISSION",
    "BEDROCK_ELF_ENTRY_SEGMENT_CONTEXT",
    "BEDROCK_ELF_ENTRY_READINESS",
    "BEDROCK_ELF_ENTRY_CLEARED_REGISTER",
)


class UnmappedRelocationExpressionError(ValueError):
    """A relocation expression has no LLVM/LLD projection."""


class LlvmRelocationProjection(NamedTuple):
    relocation: Relocation
    lld_expression: str


def project_abi(project: ElfAbiProjection) -> tuple[LlvmRelocationProjection, ...]:
    return tuple(
        LlvmRelocationProjection(relocation, _lld_expression(relocation))
        for relocation in sorted(project.relocations, key=lambda item: item.value)
    )


def _inputs(context) -> ElfAbiProjection:
    project = context.workspace.require_provider("abi.elf")
    isa = context.workspace.require_provider("isa")
    return context.shared_result((project_elf_abi, id(project), id(isa)), lambda: project_elf_abi(project, isa))


def validate(definition, context) -> None:
    project_abi(_inputs(context))


def generate(definition, context: ArtifactGenerationContext) -> GeneratedArtifactSet:
    project = _inputs(context)
    projection = project_abi(project)
    return GeneratedArtifactSet(
        (
            GeneratedArtifact(definition.outputs["relocations"], _render_relocations([item.relocation for item in projection])),
            GeneratedArtifact(definition.outputs["catalog"], _render_catalog(project, projection)),
        ),
        definition.id,
    )


def _render_relocations(relocations: list[Relocation]) -> str:
    lines = [
        "//===-- Bedrock.def - generated ELF relocations ----------------*- C++ -*-===//",
        "//",
        "// Generated by spec/artifacts/llvm-elf-abi. Do not edit.",
        "//",
        "//===----------------------------------------------------------------------===//",
        "",
        "#ifndef ELF_RELOC",
        '#error "ELF_RELOC must be defined"',
        "#endif",
        "",
    ]
    lines.extend(f"ELF_RELOC({item.id}, {item.value})" for item in relocations)
    lines.append("")
    return "\n".join(lines)


def _render_catalog(
    project: ElfAbiProjection, projection: tuple[LlvmRelocationProjection, ...]
) -> str:
    lines = [
        "//===-- BedrockGenELFABI.inc - generated ELF ABI data --------*- C++ -*-===//",
        "//",
        "// Generated by spec/artifacts/llvm-elf-abi. Do not edit.",
        "// Define any BEDROCK_ELF_* macro before including this file to consume",
        "// that record family. Undefined macros default to no-ops.",
        "//",
        "// BEDROCK_ELF_RELOCATION(name, value, family, resultKind, widthBits,",
        "//                         isSigned, lldExpression, calculation, field)",
        "// BEDROCK_ELF_RELAXATION(source, target)",
        "// BEDROCK_ELF_CODE_MODEL(id, placement, strategy)",
        "// BEDROCK_ELF_CODE_MODEL_RELOCATION(model, relocation)",
        "// BEDROCK_ELF_TLS_MODEL(id, baseRegister, protocol, selection)",
        "// BEDROCK_ELF_TLS_MODEL_RELOCATION(model, relocation)",
        "// BEDROCK_ELF_TLS_PROPERTY(model, property, value)",
        "// BEDROCK_ELF_LINKAGE_PROTOCOL(id)",
        "// BEDROCK_ELF_LINKAGE_STEP(protocol, index, instruction, form, relocation)",
        "// BEDROCK_ELF_LINKAGE_REGISTER(protocol, disposition, register)",
        "// BEDROCK_ELF_LINKAGE_PROPERTY(protocol, property, value)",
        "// BEDROCK_ELF_DEBUG_REGISTER_RANGE(id, first, last, status, condition)",
        "// BEDROCK_ELF_DEBUG_REGISTER_MAPPING(id, number, register)",
        "// BEDROCK_ELF_ENTRY_STATE(pc, pcSource, sp, stackAlignment,",
        "//                         tlsBase, payloadOwner)",
        "// BEDROCK_ELF_ENTRY_STACK_PERMISSION(permission)",
        "// BEDROCK_ELF_ENTRY_SEGMENT_CONTEXT(role, register)",
        "// BEDROCK_ELF_ENTRY_READINESS(requirement)",
        "// BEDROCK_ELF_ENTRY_CLEARED_REGISTER(register)",
        "//",
        "//===----------------------------------------------------------------------===//",
        "",
    ]
    lines.extend(_macro_defaults())

    for projected in projection:
        relocation = projected.relocation
        result = relocation.result
        lines.append(
            "BEDROCK_ELF_RELOCATION("
            + ", ".join(
                (
                    relocation.id,
                    str(relocation.value),
                    _token(relocation.family or "none"),
                    _token(result.kind.value),
                    str(result.width_bits or 0),
                    "1" if result.signed else "0",
                    projected.lld_expression,
                    _c_string(relocation.calculation.code),
                    _c_string(
                        project.relocation_fields[relocation.reference].id
                        if relocation.field
                        else ""
                    ),
                )
            )
            + ")"
        )
    for source, target in project.relaxations:
        lines.append(f"BEDROCK_ELF_RELAXATION({source.id}, {target.id})")

    for code_model in sorted(project.code_models, key=lambda item: item.id):
        properties = dict(project.properties[code_model.reference])
        lines.append(
            f"BEDROCK_ELF_CODE_MODEL({code_model.id}, "
            f"{_c_string(str(properties[('placement',)]))}, "
            f"{_c_string(str(properties[('strategy',)]))})"
        )
        for model, relocation in project.code_model_relocations:
            if model is code_model:
                lines.append(f"BEDROCK_ELF_CODE_MODEL_RELOCATION({model.id}, {relocation.id})")

    tls_registers = {model.reference: register for model, register in project.tls_registers}
    tls_protocols = {model.reference: protocol for model, protocol in project.tls_protocols}
    for tls_model in sorted(project.tls_models, key=lambda item: item.id):
        register = tls_registers.get(tls_model.reference)
        protocol = tls_protocols.get(tls_model.reference)
        base = "NONE" if register is None else register.id
        protocol_id = "NONE" if protocol is None else protocol.id
        properties = dict(project.properties[tls_model.reference])
        lines.append(
            f"BEDROCK_ELF_TLS_MODEL({tls_model.id}, {base}, {protocol_id}, "
            f"{_c_string(str(properties[('selection',)]))})"
        )
        for model, relocation in project.tls_relocations:
            if model is tls_model:
                lines.append(f"BEDROCK_ELF_TLS_MODEL_RELOCATION({model.id}, {relocation.id})")
        lines.extend(_property_lines(
            "BEDROCK_ELF_TLS_PROPERTY", tls_model.id,
            tuple((path, value) for path, value in project.properties[tls_model.reference] if path != ("selection",)),
        ))

    for assignment in sorted(
        project.debug_assignments, key=lambda item: item.first
    ):
        range_name = (
            f"RESERVED_{assignment.first}"
            if assignment.status == "reserved"
            else assignment.group
        )
        last = "UNBOUNDED" if assignment.last is None else str(assignment.last)
        lines.append(
            f"BEDROCK_ELF_DEBUG_REGISTER_RANGE({range_name}, "
            f"{assignment.first}, {last}, {_token(assignment.status)}, "
            f"{_c_string(assignment.condition or '')})"
        )
        for offset, register in enumerate(assignment.registers):
            lines.append(
                f"BEDROCK_ELF_DEBUG_REGISTER_MAPPING({range_name}, "
                f"{assignment.first + offset}, {register.id})"
            )

    state = project.process_entry
    tls_base = (
        "NONE" if state.tls_base is None else state.tls_base.id
    )
    lines.append(
        f"BEDROCK_ELF_ENTRY_STATE("
        f"{state.entry_point.id}, "
        f"{_c_string(state.entry_point_source)}, {state.stack.id}, "
        f"{state.stack_alignment_bytes}, {tls_base}, "
        f"{_c_string(state.payload_owner)})"
    )
    for permission in state.stack_permissions:
        lines.append(f"BEDROCK_ELF_ENTRY_STACK_PERMISSION({_token(permission)})")
    for role, register in state.segment_contexts.items():
        lines.append(
            f"BEDROCK_ELF_ENTRY_SEGMENT_CONTEXT({_token(role)}, "
            f"{register.id})"
        )
    for requirement in state.readiness:
        lines.append(f"BEDROCK_ELF_ENTRY_READINESS({_token(requirement)})")
    for register in state.cleared:
        lines.append(
            f"BEDROCK_ELF_ENTRY_CLEARED_REGISTER({register.id})"
        )

    steps_by_protocol = {protocol.reference: steps for protocol, steps in project.linkage_steps}
    for protocol in sorted(project.linkage_protocols, key=lambda item: item.id):
        lines.append(f"BEDROCK_ELF_LINKAGE_PROTOCOL({protocol.id})")
        for index, (instruction, form, relocation) in enumerate(steps_by_protocol[protocol.reference]):
            relocation_id = "NONE" if relocation is None else relocation.id
            lines.append(
                f"BEDROCK_ELF_LINKAGE_STEP({protocol.id}, {index}, "
                f"{instruction.instruction.mnemonic}, {_c_string(form or '')}, {relocation_id})"
            )
        for owner, disposition, registers in project.linkage_state:
            if owner is protocol:
                for register in registers:
                    lines.append(f"BEDROCK_ELF_LINKAGE_REGISTER({protocol.id}, {_token(disposition)}, {register.id})")
        lines.extend(_property_lines("BEDROCK_ELF_LINKAGE_PROPERTY", protocol.id, project.properties[protocol.reference]))

    lines.extend(_macro_cleanup())
    lines.append("")
    return "\n".join(lines)


def _lld_expression(relocation: Relocation) -> str:
    if relocation.id == "R_BEDROCK_NONE":
        return "NONE"
    if relocation.id == "R_BEDROCK_TLSDESC_CALL":
        return "TLSDESC_CALL"
    signature = _expression_signature(relocation.calculation.expression)
    try:
        return _LLD_EXPRESSION_SIGNATURES[signature]
    except KeyError as error:
        raise UnmappedRelocationExpressionError(
            f"{relocation.source}: no LLVM/LLD expression mapping for "
            f"{relocation.calculation.code!r} ({signature})"
        ) from error


def _expression_signature(expression: RelocationExpression) -> str:
    if expression.kind == "integer":
        assert expression.value is not None
        return str(expression.value)
    if expression.kind == "term":
        assert expression.name is not None
        return expression.name
    if expression.kind == "neg":
        return f"(- {_expression_signature(expression.operands[0])})"
    if expression.kind in {"add", "sub"}:
        operator = "+" if expression.kind == "add" else "-"
        return (
            f"({operator} {_expression_signature(expression.operands[0])} "
            f"{_expression_signature(expression.operands[1])})"
        )
    assert expression.kind == "call" and expression.name is not None
    operands = ",".join(_expression_signature(item) for item in expression.operands)
    return f"{expression.name}({operands})"


def _property_lines(macro: str, owner: str, properties) -> list[str]:
    return [
        f"{macro}({owner}, {_token('_'.join(str(part) for part in path))}, {_scalar(value)})"
        for path, value in properties
    ]


def _macro_defaults() -> list[str]:
    lines: list[str] = []
    for macro in _MACROS:
        marker = f"BEDROCK_GEN_DEFINED_{macro}"
        lines.extend(
            (
                f"#ifndef {macro}",
                f"#define {macro}(...)",
                f"#define {marker}",
                "#endif",
            )
        )
    lines.append("")
    return lines


def _macro_cleanup() -> list[str]:
    lines = [""]
    for macro in _MACROS:
        marker = f"BEDROCK_GEN_DEFINED_{macro}"
        lines.extend(
            (
                f"#ifdef {marker}",
                f"#undef {macro}",
                f"#undef {marker}",
                "#endif",
            )
        )
    return lines


def _token(value: str) -> str:
    token = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
    if not token or token[0].isdigit():
        token = "VALUE_" + token
    return token


def _scalar(value: object) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return _c_string(value)
    raise TypeError(f"ELF ABI property cannot be projected as a scalar: {value!r}")


def _c_string(value: str) -> str:
    escaped = []
    for character in value:
        if character in ('\\', '"', '?'):
            escaped.append('\\' + character)
        elif ord(character) < 32 or ord(character) == 127:
            escaped.append(f"\\{ord(character):03o}")
        else:
            escaped.append(character)
    return '"' + ''.join(escaped) + '"'
